# Generated by Django 3.0.1 on 2020-01-05 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cost_ww', models.DecimalField(decimal_places=2, default=0.8, max_digits=10)),
                ('cost_brezn', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('cost_mustard', models.DecimalField(decimal_places=2, default=0.15, max_digits=10)),
                ('ordering_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WW_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weißwiaschd', models.IntegerField(default=0)),
                ('brezn', models.IntegerField(default=0)),
                ('purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.SlugField(unique=True)),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwlist.Friday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('previous_balance_pk', models.IntegerField(default=-1)),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwlist.Friday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
