# Generated by Django 3.0.1 on 2020-01-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwlist', '0002_auto_20200105_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ww_order',
            name='ww',
            field=models.IntegerField(default=0, verbose_name='WW'),
        ),
    ]
