# Generated by Django 3.0.1 on 2020-01-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwlist', '0003_auto_20200105_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='mail_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
