# Generated by Django 3.0.1 on 2020-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwlist', '0005_initial_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ('-friday__date', 'balance')},
        ),
        migrations.AlterModelOptions(
            name='friday',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='initial_balance',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='ww_order',
            options={'ordering': ('-friday__date',)},
        ),
        migrations.AlterField(
            model_name='ww_order',
            name='brezn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ww_order',
            name='ww',
            field=models.PositiveIntegerField(default=0, verbose_name='WW'),
        ),
    ]
